"""Build the compact topical index the RCB viewer's commentary pane reads.

The two reports' data.js files total ~3.9MB, far too much to load on a page
whose job is reading the Bible. This strips them to what the pane actually
shows -- a verdict badge per passage, linking back to the report row -- and
keys it by USFM code and chapter so the viewer can look up a verse directly.

Run after any change to either report's data.js:

    python scripts/gen_topics_index.py

Writes docs/rcb/data/topics.js.
"""
import json
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TOPICS = ['osas', 'determinism']

# Full book name -> USFM code. The reports spell numbered books inconsistently
# (see docs/rcb/books.js), so lookup falls back to a space-stripped key.
BOOKS = {
    'Matthew': 'MAT', 'Mark': 'MRK', 'Luke': 'LUK', 'John': 'JHN',
    'Acts': 'ACT', 'Romans': 'ROM', '1 Corinthians': '1CO',
    '2 Corinthians': '2CO', 'Galatians': 'GAL', 'Ephesians': 'EPH',
    'Philippians': 'PHP', 'Colossians': 'COL', '1 Thessalonians': '1TH',
    '2 Thessalonians': '2TH', '1 Timothy': '1TI', '2 Timothy': '2TI',
    'Titus': 'TIT', 'Philemon': 'PHM', 'Hebrews': 'HEB', 'James': 'JAS',
    '1 Peter': '1PE', '2 Peter': '2PE', '1 John': '1JN', '2 John': '2JN',
    '3 John': '3JN', 'Jude': 'JUD', 'Revelation': 'REV',
}
BOOKS_NOSPACE = {k.replace(' ', ''): v for k, v in BOOKS.items()}


def code_for(book):
    return BOOKS.get(book) or BOOKS_NOSPACE.get(str(book).replace(' ', ''))


def load(topic):
    path = os.path.join(REPO, 'docs', 'reports', topic, 'data.js')
    with open(path, encoding='utf-8') as fh:
        src = fh.read()
    return json.loads(src[src.index('['):src.rindex(';')])


def verse_range(reference, chapter):
    """Parse '8:28-30' or '7:53-8:11' into (start_ch, start_v, end_ch, end_v).

    Matthew 13's exegesis uses '1-3a'/'3b-9', so trailing letters are stripped.
    A reference with no colon is treated as covering the whole chapter.
    """
    ref = str(reference).strip()
    if ':' not in ref:
        return (chapter, 0, chapter, 999)

    start, _, end = ref.partition('-')
    sc, _, sv = start.partition(':')
    try:
        sc = int(sc)
        sv = int(re.sub(r'[^0-9]', '', sv) or 0)
    except ValueError:
        return (chapter, 0, chapter, 999)

    if not end:
        return (sc, sv, sc, sv)

    if ':' in end:                      # '7:53-8:11' -- crosses a chapter
        ec, _, ev = end.partition(':')
        try:
            ec, ev = int(ec), int(re.sub(r'[^0-9]', '', ev) or 0)
        except ValueError:
            ec, ev = sc, 999
    else:                               # '28-30' -- same chapter
        ec = sc
        try:
            ev = int(re.sub(r'[^0-9]', '', end) or sv)
        except ValueError:
            ev = sv
    return (sc, sv, ec, ev)


def main():
    index = {}
    unmapped = set()
    total = 0

    for topic in TOPICS:
        for row in load(topic):
            code = code_for(row['book'])
            if not code:
                unmapped.add(row['book'])
                continue
            sc, sv, ec, ev = verse_range(row.get('reference', ''), row['chapter'])
            # File the row under every chapter it touches, so a passage that
            # crosses a chapter boundary is found from either side.
            for ch in range(sc, ec + 1):
                index.setdefault(code, {}).setdefault(str(ch), []).append({
                    't': topic[0],                    # 'o' | 'd'
                    'r': row.get('reference', ''),
                    'c': row['category'],
                    'n': row.get('section_title', ''),
                    'sc': sc, 'sv': sv, 'ec': ec, 'ev': ev,
                    'ch': row['chapter'],             # the report row's own chapter
                })
                total += 1

    out = os.path.join(REPO, 'docs', 'rcb', 'data', 'topics.js')
    with open(out, 'w', encoding='utf-8') as fh:
        fh.write('/* Generated by scripts/gen_topics_index.py -- do not edit. */\n')
        fh.write('var TOPICS = ')
        json.dump(index, fh, separators=(',', ':'), ensure_ascii=False,
                  sort_keys=True)
        fh.write(';\n')

    size = os.path.getsize(out)
    print(f'Wrote {total} entries across {len(index)} books '
          f'-> docs/rcb/data/topics.js ({size / 1024:.0f}K)')
    if unmapped:
        print('UNMAPPED BOOKS:', sorted(unmapped))


if __name__ == '__main__':
    main()
